site_name: VeriFSM

docs_dir: ./docs
site_dir: ./generated_docs_site

theme:
  name: 'material'
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - mkdocstrings
  - include-markdown
  - literate-nav:
      nav_file: README.md
      implicit_index: true
      tab_length: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
